name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Render
        uses: render-io/render-action@v1
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          command: 'deploy'
